version: "3"

services:
  vail-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10002:8000

    volumes:
      - vail_scraper:/opt/data
  questdb:
    image: questdb/questdb:7.4.2
    ports:
      - 10003:9000 # Web and API
    volumes:
      - questdb:/var/lib/questdb


volumes:
  vail_scraper:
  questdb:
