version: "3"

services:
  vail-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 10002:8000
    depends_on:
      questdb:
        condition: service_healthy
    volumes:
      - vail_scraper:/opt/data
  questdb:
    build:
      context: .
      dockerfile: questdb.Dockerfile
    ports:
      - 10003:9000 # Web and API
      - 10005:8812 # Postgres
    volumes:
      - questdb:/var/lib/questdb
    healthcheck:
      test: curl --fail http://localhost:9000 || exit 1
      interval: 5s
      retries: 5
      start_period: 1s
      timeout: 10s
  meilisearch:
    image: getmeili/meilisearch:v1.8
    ports:
      - 10006:7700
    volumes:
      - meilisearch:/meili_data



volumes:
  vail_scraper:
  questdb:
  meilisearch:
