mode = "scraper"
enabled = true
user_agent = "VailGrafanaScraper v/1.0 (contact info here)"

[rate_limiter]
times = 2
per = 3

[user]
email = ""
password = ""

[bans]
accelbyte = false

[database.sqlite]
url = "/opt/data/db.sqlite"
[database.quest]
http_url = "http://questdb:9000"
postgres_url = "postgres://admin:quest@questdb:"
[database.meilisearch]
url = "http://melisearch:7700"
